name: build and test

on:
  push:
  pull_request:
   branches: [ main ]

env:
  DOTNET_VERSION: '6.0.202' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test
