name: build and test

on:
  push:
  pull_request:
   branches: [ main ]
jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Test
      run: dotnet test --no-restore --filter FullyQualifiedName!~Android
